services:
  varc:
    image: golang:1.21-alpine
    container_name: app
    working_dir: /app
    volumes:
      - .:/app            
      - go-mod-cache:/go/pkg/mod
    command: /bin/sh        
    tty: true
    stdin_open: true
    environment:
      - GO111MODULE=on

volumes:
  go-mod-cache:
