services:
  varc:
    image: golang:1.21-alpine
    container_name: app
    working_dir: /app
    volumes:
      - .:/app             # Mount current folder into /app
      - go-mod-cache:/go/pkg/mod   # Cache dependencies
    command: /bin/sh        # Start a shell by default
    tty: true
    stdin_open: true
    environment:
      - GO111MODULE=on

volumes:
  go-mod-cache:
